🌟 Exercice 1 : Création et manipulation de tableaux

In [1]:
import numpy as np
# Créez un tableau NumPy unidimensionnel contenant les nombres de 0 à 9.
array_1d = np.array(range(10))
print("Tableau unidimensionnel de 0 à 9:")
print("array", array_1d)

Tableau unidimensionnel de 0 à 9:
array [0 1 2 3 4 5 6 7 8 9]


🌟 Exercice 2 : Conversion de type et opérations sur les tableaux

In [2]:
# Convertissez une liste [3.14, 2.17, 0, 1, 2]en un tableau NumPy et convertissez son type de données en entier
list_floats = [3.14, 2.17, 0, 1, 2]
array_ints = np.array(list_floats, dtype=int)
print("\nTableau converti en entier:")
print("array", array_ints)


Tableau converti en entier:
array [3 2 0 1 2]


🌟 Exercice 3 : Travailler avec des tableaux multidimensionnels

In [3]:
# Créez un tableau NumPy 3x3 avec des valeurs allant de 1 à 9
array_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nTableau 3x3 avec des valeurs de 1 à 9:")
print("array", array_3x3)   


Tableau 3x3 avec des valeurs de 1 à 9:
array [[1 2 3]
 [4 5 6]
 [7 8 9]]


🌟 Exercice 4 : Création d'un tableau multidimensionnel avec des nombres aléatoires

In [4]:
#Créez un tableau NumPy 2D de forme (4, 5) rempli de nombres aléatoires.
array_random = np.random.rand(4, 5)
print("\nTableau 2D de forme (4, 5) rempli de nombres aléatoires:")
print("array", array_random)


Tableau 2D de forme (4, 5) rempli de nombres aléatoires:
array [[0.48566539 0.39423367 0.75937219 0.07828496 0.13174854]
 [0.067949   0.74459919 0.425142   0.74423977 0.78178566]
 [0.968205   0.45019558 0.7202242  0.54898567 0.18742751]
 [0.57968715 0.92416908 0.21593653 0.50405434 0.19476995]]


🌟 Exercice 5 : Indexation des tableaux

In [5]:
# Sélectionnez la deuxième ligne d'un tableau NumPy 2D donné.
import numpy as np

array = np.array([[21,22,23,22,22],
                  [20, 21, 22, 23, 24],
                  [21,22,23,22,22]])

deuxieme_ligne = array[1, :]
print(deuxieme_ligne)


[20 21 22 23 24]


🌟 Exercice 6 : Inversion des éléments

In [6]:
# Inverser l'ordre des éléments d'un tableau NumPy 1D donné (le premier élément devient le dernier).
mon_array=np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
mon_array_inversé = mon_array[::-1]
print("Tableau inversé:")
print("array", mon_array_inversé)


Tableau inversé:
array [0 1 2 3 4 5 6 7 8 9]


🌟 Exercice 7 : Matrice identité

In [13]:
#Créez une matrice identité 4x4 à l'aide de NumPy.\
matrice_identite = np.eye(4)
print("\nMatrice identité 4x4:")
print(f"array({matrice_identite})")


Matrice identité 4x4:
array([[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]])


🌟 Exercice 8 : Fonctions agrégées simples

In [ ]:

array = np.arange(0, 10)   # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

total   = np.sum(array)
moyenne = np.mean(array)

print(f"Sum: {total}, Average: {moyenne}")

Sum: 45, Average: 4.5


 Exercice 9 : Créer un tableau et modifier sa structure

In [2]:
# Créez un tableau NumPy avec des éléments de 1 à 20 ; puis remodelez-le en une matrice 4x5
import numpy as np
array_1d = np.array(range(1, 21))
matrice_4x5 = array_1d.reshape(4, 5)
print(f"Array 1D: {array_1d}")
print(f"Matrice 4x5: {matrice_4x5}")

Array 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Matrice 4x5: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


🌟 Exercice 10 : Sélection conditionnelle des valeurs

In [3]:
# Extraire tous les nombres impairs d'un tableau NumPy donné
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
nombres_impairs = array[array % 2 != 0] 
print("Nombres impairs extraits du tableau:")
print("array", nombres_impairs)

Nombres impairs extraits du tableau:
array [1 3 5 7 9]
